services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: caddfe-php
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/cache:/var/www/html/storage/cache
      - ./storage/framework:/var/www/html/storage/framework
    env_file: .env
